minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2102.12'
  - '@angular-devkit/core@21.2.12'
  - '@angular-devkit/schematics@21.2.12'
  - '@angular/build@21.2.12'
  - '@angular/cli@21.2.12'
  - '@schematics/angular@21.2.12'
